---

jobs:
  include:
    - name: Unit Tests 3.5
      language: python
      os: linux
      dist: bionic
      python:
        - '3.5'
      env:
        - RUNTESTS=1
    - name: Unit Tests 3.6
      language: python
      os: linux
      dist: bionic
      python:
        - '3.6'
      env:
        - RUNTESTS=1
    - name: Unit Tests 3.7
      language: python
      os: linux
      dist: bionic
      python:
        - '3.7'
      env:
        - RUNTESTS=1
    - name: Unit Tests 3.8
      language: python
      os: linux
      dist: bionic
      python:
        - '3.8'
      env:
        - RUNTESTS=1
    - name: Build and Upload Linux Wheels
      os: linux
      dist: bionic
      language: python
      python:
        - '3.7'
      env:
        - RUNTESTS=0
    - name: Build and Upload MacOS 10.14 Wheels
      os: osx
      osx_image: xcode11.2
      language: c
      env:
        - RUNTESTS=0
    - name: Build and Upload MacOS 10.13 Wheels
      os: osx
      osx_image: xcode10.1
      env:
        - RUNTESTS=0
install:
  - if [[ "$RUNTESTS" == "1" ]]; then python3 -m pip install -U pip;            fi
  - if [[ "$RUNTESTS" == "1" ]]; then python3 -m pip install .;                 fi
script:
  - if [[ "$RUNTESTS" == "1" ]]; then echo we should test stuff; fi

  - if [[ "$RUNTESTS" == "0" && "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-manylinux.sh || travis_terminate 1; fi
  - if [[ "$RUNTESTS" == "0" && "$TRAVIS_OS_NAME" == "osx"   ]]; then ./build-macos.sh     || travis_terminate 1; fi

  - |
    if [[ "$RUNTESTS" == "0" ]]; then
      ls -l ./wheelhouse
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        if [[ "$TRAVIS_BRANCH" == "master" ]]; then
          set -e
          pip3 install twine
          python3 -m twine upload --non-interactive --skip-existing --verbose -u __token__ ./wheelhouse/*
        fi
      fi
    fi
